# Generated by Django 5.1.3 on 2025-06-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sondages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choix_text", models.CharField(max_length=250)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sondages.question",
                    ),
                ),
            ],
        ),
    ]
