# Generated by Django 5.1.3 on 2025-06-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sondages", "0002_choix"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="publication_date",
            new_name="pub_date",
        ),
    ]
